project:
  type: website
  output-dir: docs
  preview:
    port: 7780

website:
  title: "NLP Specialization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
  site-url: https://orenbochman.github.io/notes-nlp/
  description: "Course and Research notes"
  repo-url: https://github.com/OrenBochman/notes-nlp/
  repo-actions: [edit, issue]
  #favicon: favicon.ico
  sidebar:
    #background: "#f1de67" # Arylide Yellow
    contents:
      - section: "Classification & Vector Spaces"
        contents:                
          - href: posts/c1w1/index.qmd
            text: Logistic Regression
          - href: posts/c1w2/index.qmd
            text: Probability and Bayes Rule
          - href: posts/c1w3/index.qmd
            text: Vector Space Models and PCA
          - href: posts/c1w4/index.qmd
            text: Machine Translation and Document Search via KNN
          - href: posts/c1lab0/index.qmd
            text: Lab on preprocessing
          - href: posts/c1lab1/index.qmd
            text: Assignment 1 Logistic Regression
          - href: posts/c1lab2/index.qmd
            text: Lab on Building and Visualizing word frequencies
          - href: posts/c1lab3/index.qmd
            text: Lab on visualizing tweets and the Logistic Regression model            
      - section: "Probabilistic Models"
        contents:
          - href: posts/c2w1/index.qmd
            text: Autocorrect and Dynamic Programming
          - href: posts/c2w2/index.qmd
            text: Part of Speech Tagging and Hidden Markov Models
          - href: posts/c2w3/index.qmd
            text: Autocomplete and Language Models
          - href: posts/c2w4/index.qmd
            text: Word embeddings with neural networks
      - section: "Sequence Models"
        contents:
          - href: posts/c3w1/index.qmd
            text: Neural Machine Translation
          - href: posts/c3w2/index.qmd
            text: Text Summarization
          - href: posts/c3w3/index.qmd
            text: Question Answering
          - href: posts/c3w4/index.qmd
            text: Chat Bots
      - section: "NLP with Attention Models"
        contents:               
          - href: posts/c4w1/index.qmd
            text: Neural Machine Translation
          - href: posts/c4w2/index.qmd
            text: Text Summarization
          - href: posts/c4w3/index.qmd
            text: Question Answering
          - href: posts/c4w4/index.qmd
            text: Chat Bots
  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023-2025, Oren Bochman"
    background: "#AB0520" # AZ Red

date-format: full
date: last-modified

format:
  html:
    theme:
      light: [flatly]
      dark: [darkly]
      #light: [flatly, style/isl.scss]
      #dark: [darkly,  style/isl.scss, style/dark.scss]
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 1600px
      margin-width: 420px
      gutter-width: 1.5rem
    toc: true
    page-layout: full
    from: "markdown+emoji"
    reference-location: margin
    citation: true
    citation-location: document
    ipynb-shell-interactivity: all 
    anchor-sections: true
    code-fold: false
    html-math-method: katex
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    smooth-scroll: true
    image: images/nlp-brain-wordcloud.jpg
    #title-block-banner: images/banner_black_3.jpg
    image-placeholder: images/dnn_cover.png
    title-block-banner: images/banner_deep.jpg


bibliography: references.bib

editor: 
  markdown: 
    wrap: sentence
    #wrap: 72    

execute:
  freeze: auto
  cache: true