---
date: 2025-02-18
title: "Domination Games"
subtitle: "Establishing hierarchies"
categories: 
    - Game Theory
    - Agent Based Models
    - Social Structures
    - Hierarchies
---

## Motivation

In a previous post titled [Samurai's world](..\25-02-17-samurai-world\index.qmd), I considered the complex states and a framing game of a Lewis signaling game for which  the requisite linguistics aspects of politeness and formality should emerge out of language evolution

Today though I'd like to pause from signaling for a bit and 
consider the establishment of hierarchies in a multi-agent system. This is also an extension that seems of interest to 
Sugarscape and other agent based models where one might be interested in the emergence of social hierarchies.

For language generation we may assign the hierarchy arbitrarily. But to speed learning we may want both the language and the hierarchy to emerge together. This can let us consider how different social structures may result in 
different linguistic structures.

## Establishing a hierarchy.

So lets lay down some ground rules. In our society the agents are initially an Egalitarian society meaning they are without a hierarchy or language. They are heterogenous and they can also evolve and learn via RL. 

The game takes a decentralized forms for agent interactions and we are generally interested in finding an form of incentive often embodied as rule and or a utility that can when maximized individually leads to better overall performance in the society. This can be in the carrying capacity, mean wealth, or social welfare or expected progeny.

As the simulation progresses conditions may change to favor different strategies. For example if the carrying capacity of the environment changes, the agents may need to change their strategy to adapt. Agents less fit may die out, while fitter agents may migrate to greener pastures.

Eventually though the agents will have to interact with each other strategically to maximize their utility. Agents that don't learn to do so will face greater risks of being eliminated. Further on agents may need to cooperate, coordinate and compete as groups to survive. It is somewhere along this axis that learning language and establishing social hierarchies may be increasingly beneficial.

Finally although the focus here is growing hierarchies I think that we should agree that that we are interested in the interplay of social structures and language.

## Dual view of Hierarchies

In terms of society the cost of a leader's actions and decisions may have far reaching impact on the future of group. The benefits and costs may be in proportion to the group's size. Given the costs of bad decisions larger groups have vested interests in seeing that the leaders are competent and that the group's resources are used wisely. 

The leader on the other hand may like to do as they please, avoid criticism and challenges to their authority. They may also wish to avoid the costs of bad decisions by foisting them onto others. To do this they would like to reduce the group they are accountable to.

### The principal-agent dilemma

The ability of leaders to pick members of the hierarchy based on loyalty rather then merit subverts the society's goals yet this is often the paths taken by leaders.

Looking at emergent hierarchies we would like to study how the group can best select a hierarchy and leaders that primarily serve the group's interests. The leaders of the hierarchy may try to game the system to serve their own interests. This is called the principal-agent dilemma and is a common problem in economics and politics. And we should formalize this aspect of the the game as it appears there are no political systems that are immune to this problem.

## Emergent Hierarchies

Dominance hierarchy is common in the nature. While most of the time it is established by physical characteristics, we have many examples where other mechanisms. The use of brute force is risky for the individual and in the long term for the group.

- Egalitarian
- Age group - initially all have the same age
- Dominance - some agents are stronger
- Egalitarian meaning no hierarchy
- Partiarchal - succession is by the oldest son progeny of the leader
- Matriarchal - succession is by the oldest daughter progeny of the leader
- Oligarchy - some agents are more fit in harvesting resources and may be able to increase this advantage via trade. This should lead to specialization and division of labor under suitable circumstances.
- Oligrachy with welfare. In Japan the CEO's pay may only be 20x that of the lowest paid employee. Another way to improve welfare is to require an agent to share wealth when  they come into contact with agents which are worse off. These gifts though can be used to keep track of social status based on amount given and received!
- Meritocracy - this is a form of hierarchy where agents are ranked by their ability to perform a task. This means that there are many possible hierarchies in a group. However specialization implies we will consider individuals in a group for their top roles for skills that are have unmet demand by more qualified agents.
- Aristocracy - authority is based on birthright and passes by rules of succession. Land ownership and rents dervided from these are restricted to a few families. Power is derived from wealth and influence can be increased by wealth, marriage, and alliances.


Another aspect of dominance hierarchies is that they can lead to chaos or disharmony whenever the leader's ability falls into   question. This can lead to a challenge to the leader's authority. 



## Games of domination

Leaders will wish to deter challenges to their authority i.e. disagreements over their actions or decisions for the group. This can be done in many ways. Here are a few:

- they can do this by being requiring that challengers first qualify
- i.e. win a tournament that places them as the current challenger
- they may need to also bring some resource, i.e. a wager, to the table
- the challenges require a quorum and may take place only at certain times like once a year.
- the challenged may also decide the terms of the challenge like the weapons used and the stakes involved.

They may go further yet by outlawing such challenges and punishing those who do so.
This leads to [selectorate](https://en.wikipedia.org/wiki/Selectorate_theory) theory where the leader may want to keep the selectorate small to reduce the risk of being challenged. I.e. the pool of people who can pose challenges are kept small and given high incentives to support the leader. This may be done by rewarding them with resources or status well beyond they could achieve on their own.

So in terms of this game:

if $X < Y \wedge X > Z\ \forall(Z < Y)$ X then X may challenge Y. Y may however consider his and X's interinsics and skill abd set the terms most favorable to him.

## winner takes all:

- The most extreme format of domination, yet one which may also deter challenges to the leader
- The winner takes the loser's life,  status, possession, mates, and can kill his progeny and may impose similar punishments to the loser's group.+
- Leaders will want to avoid having to play in this game and may 

In the next three sections we will consider social structure that are common both family and state levels and are setup to maintain a heirarchy.

## Patriarchy

- the oldest son progeny of the leader takes the leader's social role in the event of the leader's death.
- the leader may also decide the heir to the throne is someone else other than his oldest son.

## Matriarchy

- the oldest daughter progeny of the leader takes the leader's social role in the event of the leader's death.

## Succession

- the leaders oldest son or daughter may be the heir to the throne.
- if the leader has no children, the succession is by the oldest direct descendant of the most recent leader.



It seems that our agents might need a leaders. And the leaders need a leader too. This might be a prequisite for planning in which an agent assigns tasks to other agents. This wouldn't work well if all agents shared the same role. 

One way to go is by age of the agent. The older agents are the leaders. But what if there are no older agents in the group?
Another aspect is skill and specialization. To be assigned certain roles agents need to demonstrate skills. This may involve rites of passage or other tests to initiate agents into a new role. E.g. masai hunting a lion solo with a spear 

We need a game for establishing a hierarchy.

The game of domination can be used to create social hierarchy of agents. Domination can be risky and costly. But once established it can be used to assign tasks. This means that any tasked one is given may be reassigned to a lower status agent. 

The rewards for such social tasks may be shared.
- they may be shared by the group
- they may be given to the leader to keep/share/distribute/assign
- they may be given 

- It requires time.
- It requires witnesses.
- Agents are at risk of losing face 
- Agents may also risk injury or death if the opponent is stronger.
- An agent of lower or equal status may challange another agent to a duel. 
- The challange may be 
- The winner takes the loser's status. 
- The loser is demoted to the status of the winner.
- The winner may also take the loser's resources.
- The winner may also take the loser's mate.
- The winner may also take the loser's life. 
- This has a cost in terms of resources and status.
- Viewers may wager on the outcome of the duel.
- The challenged decides the terms of the duel.
    - The duel may be to the death or to first blood.
    - The duel may be non-lethal e.g. a mating dance or call

- Note: that the ideal leader is not always the strongest or most effective killer. But perhaps the one who can best assign tasks and resources to make the group most effective.
- duels to the death may be effective for deterring challenges to the leader, but they also risk the loss of one or two  valuable member of the group each time they take place.
- thus a challenge to the leader may need to qualify, say by dominating all the warriors younger then the leader.
- so we can see there may be soft or hard mechanisms for establishing a hierarchy.
- there could be multiple hierarchies in a group.
    - hunters may not want to participate in foraging tasks and so the foragers may establish their own hierarchy.
    - hunters may also decide rank by ability with a spear pow or throwing rocks.
    - elders may establish their own hierarchy and act as advisors to the leaders.


We probably want the hierarchy to be transitive.